// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRs3Wo02KY97PsEzDJw2PjuV1ezK3RAXY',
    appId: '1:988893100767:web:dbb484b03b8d91937a076a',
    messagingSenderId: '988893100767',
    projectId: 'capstone-project-54b64',
    authDomain: 'capstone-project-54b64.firebaseapp.com',
    storageBucket: 'capstone-project-54b64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASk0lnhcfqHADw-h8g8P6UBbh1uEfF8vk',
    appId: '1:988893100767:android:202c2b6f5db608da7a076a',
    messagingSenderId: '988893100767',
    projectId: 'capstone-project-54b64',
    storageBucket: 'capstone-project-54b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ0Pw8Z90S2pzl7qCKlpu1T5taK_Wi4gk',
    appId: '1:988893100767:ios:506aa83f210072f67a076a',
    messagingSenderId: '988893100767',
    projectId: 'capstone-project-54b64',
    storageBucket: 'capstone-project-54b64.appspot.com',
    iosClientId: '988893100767-917tg81s9v8rgd3fnc4idscv3tdh2r32.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ0Pw8Z90S2pzl7qCKlpu1T5taK_Wi4gk',
    appId: '1:988893100767:ios:506aa83f210072f67a076a',
    messagingSenderId: '988893100767',
    projectId: 'capstone-project-54b64',
    storageBucket: 'capstone-project-54b64.appspot.com',
    iosClientId: '988893100767-917tg81s9v8rgd3fnc4idscv3tdh2r32.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );
}
